name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-xdist

    - name: Print PYTHONPATH
      run: echo $PYTHONPATH

    - name: Run tests with coverage in parallel
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE/src:$PYTHONPATH
        pytest -n auto --cov=src --cov-report xml:coverage.xml tests/

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
